remote_theme: b2a3e8/jekyll-theme-console
title: John Rush's Blog
description: Tech blog about software development and other interesting topics
url: "https://john-rush.com"
header_pages:
  - index.md
  - about.md
style: dark
listen_for_clients_preferred_style: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

